INSERT INTO USER (USER_NAME, PASSWORD)
VALUES ('Venu', '$2y$11$B4gOVQJ/yBMTaZvfKpkyoeyr2Hjk1892jbjdMXvPEJgmA2evlHCoC');
INSERT INTO USER (USER_NAME, PASSWORD)
VALUES ('Kannuri', '$2y$11$B4gOVQJ/yBMTaZvfKpkyoeyr2Hjk1892jbjdMXvPEJgmA2evlHCoC');

INSERT INTO AUTH_USER_GROUP (USER_NAME, AUTH_GROUP)
VALUES ('Venu', 'USER');
INSERT INTO AUTH_USER_GROUP (USER_NAME, AUTH_GROUP) VALUES('Kannuri', 'ADMIN');
INSERT INTO AUTH_USER_GROUP (USER_NAME, AUTH_GROUP)
VALUES ('Kannuri', 'USER');
